imap_server: "imap.gmail.com:993"
email: "your.mail@gmail.com"
password: "yourpassword"
printer_name: "PDF"
debug: true
allowed_file_types:
  - ".pdf"
log_level: "info"
attachment_retention: "24h"
allowed_senders:
  - "sample.tester@nomail.com"