name: Release Build

on:
  push:
    branches:
      - release
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Get version
        id: get_version
        run: |
          echo "version=latest" >> $GITHUB_OUTPUT
      
      - name: Build for Multiple Platforms
        run: |
          # Create platform-specific directories
          mkdir -p releases/latest
          
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -o email-printer ./cmd/main.go
          tar czf releases/latest/email-printer-linux-amd64.tar.gz email-printer

          # Linux ARM (Raspberry Pi)
          GOOS=linux GOARCH=arm GOARM=7 go build -o email-printer ./cmd/main.go
          tar czf releases/latest/email-printer-linux-arm.tar.gz email-printer
          
          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -o email-printer ./cmd/main.go
          tar czf releases/latest/email-printer-linux-arm64.tar.gz email-printer
          
          # macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -o email-printer ./cmd/main.go
          tar czf releases/latest/email-printer-darwin-amd64.tar.gz email-printer
          
          # macOS ARM64 (M1/M2)
          GOOS=darwin GOARCH=arm64 go build -o email-printer ./cmd/main.go
          tar czf releases/latest/email-printer-darwin-arm64.tar.gz email-printer

      - name: Delete existing tag
        run: |
          git tag -d latest || true
          git push origin --delete latest || true

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          name: latest
          draft: false
          prerelease: false
          files: |
            releases/latest/email-printer-linux-amd64.tar.gz
            releases/latest/email-printer-linux-arm.tar.gz
            releases/latest/email-printer-linux-arm64.tar.gz
            releases/latest/email-printer-darwin-amd64.tar.gz
            releases/latest/email-printer-darwin-arm64.tar.gz
          body: |
            ## Email to Printer ${{ steps.get_version.outputs.version }} (Latest)
            
            ### Downloads
            - [Linux (AMD64)](releases/latest/email-printer-linux-amd64.tar.gz)
            - [Linux (ARM/Raspberry Pi)](releases/latest/email-printer-linux-arm.tar.gz)
            - [Linux (ARM64)](releases/latest/email-printer-linux-arm64.tar.gz)
            - [macOS (Intel)](releases/latest/email-printer-darwin-amd64.tar.gz)
            - [macOS (Apple Silicon)](releases/latest/email-printer-darwin-arm64.tar.gz)